### ISSUE TITLE
gym.Env의 wrapping class 작성

### ISSUE THREAD

**Issue by MrSyee** [medipixel/reinforcement_learning_examples#17]
gym wrapper로 환경에서 state를 torch.Tensor로 만들어주는 코드 작성

**Comment by Curt-Park** [comment]
Env의 wrapper는 pytorch의 tensor type으로만 핸들링하기 위함

**Comment by Curt-Park** [comment]
CPU <-> GPU 파일복사를 너무 많이 야기하여 구현을 중단
